@startuml
'https://plantuml.com/class-diagram

package application {
     class AuthorizationQueryApplication
     class AuthorizationCommandApplication
}


class AuthorizationQueryApplication {
    + queryAuthorizationList(AuthorizationQueryBO authorizationQueryBO)
}

class AuthorizationCommandApplication {
    + assignAuthorization()
    + modifyAuthorization()
    + changeAuthorizationWithEvent()
}

class AuthorizationQueryRepo {
    + queryAuthorizationList(AuthorizationQueryBO authorizationQueryBO)
}


@enduml