@startuml
'https://plantuml.com/class-diagram
top to bottom direction
package interface {
    class AuthorizationController
    class FinanceRequirementController
    class SpaceController
}


class AuthorizationController {
    + assignAuthorization()
    + modifyAuthorization()
    + removeAuthorization()
    + queryUserByBizlineAndRole()
    + queryAuthorizationDetail()
    + queryAuthorizationList()
}

class FinanceRequirementController {
    + create()
    + update()
    + userPageQuery()
    + managerPageQuery()
  }

 class SpaceController {
    + queryBusinessLineDict()
    + queryRoleDict()
  }

@enduml