@startuml
'https://plantuml.com/use-case-diagram

autonumber
autoactivate on

WEB -> AuthorizationController : 前端调用开始
AuthorizationController -> AuthorizationController : 参数校验 + 参数转化
AuthorizationController --> AuthorizationController : return
AuthorizationController -> AuthorizationCommandApplication : 分配权限
AuthorizationCommandApplication -> AuthorizationRepo : 根据权限组id获取资源信息
AuthorizationRepo -> Resource_1 ** : create
AuthorizationRepo --> AuthorizationCommandApplication : return
AuthorizationCommandApplication -> Resource_1 : 判断是否已经存在关系
Resource_1 --> AuthorizationCommandApplication : return
alt 如果没有建立过关系
    AuthorizationCommandApplication --> AuthorizationController : return, 提示前端无法删除
    AuthorizationController --> WEB : return
end alt
    AuthorizationCommandApplication -> AuthorizationCommandApplication
    AuthorizationCommandApplication -> Resource_1 : 修改聚合中的关系
    Resource_1 --> AuthorizationCommandApplication : return
    AuthorizationCommandApplication -> AuthorizationRepo : 保存新的授权关系(增量处理)
    AuthorizationRepo --> AuthorizationCommandApplication : return
group 异步调用快搭
    AuthorizationCommandApplication -\\ AuthorizationDomainService : 权限组维度，重新授权
    AuthorizationDomainService -> AuthorizationGateway : 基于业务线+角色查询空间站角色人员信息
    AuthorizationGateway --> AuthorizationDomainService : return
    AuthorizationDomainService -> Resource_1 : 汇总并且去重需要授权的人员信息
    Resource_1 --> AuthorizationDomainService : return
    AuthorizationDomainService -> KuaidaGateway : 根据授权组id查询全量数据
    KuaidaGateway --> AuthorizationDomainService : return
    AuthorizationDomainService -> Resource_1 : 获取需要授权人员信息
    Resource_1 --> AuthorizationDomainService : return
    AuthorizationDomainService -> Resource_1 : 获取需要删除人员信息
    Resource_1 --> AuthorizationDomainService : return
    AuthorizationDomainService -> KuaidaGateway : 授权人员信息
    KuaidaGateway --> AuthorizationDomainService : return
    AuthorizationDomainService -> KuaidaGateway : 取消授权人员信息
    KuaidaGateway --> AuthorizationDomainService : return
    AuthorizationDomainService --> Resource_1 !! : delete
end group
note left
    异步进行快搭授权，如果异步失败，
    需要补偿，按照业务线+角色的维度进行任务补偿
end note
AuthorizationDomainService --\\ AuthorizationCommandApplication : return

AuthorizationCommandApplication --> AuthorizationController : return
AuthorizationController --> WEB : return

@enduml