@startuml

start

:财务方案概览 状态;
:页面添加关注人;
if(财务方案概览状态) then (未推送)
    if (操作类型) then (仅添加关注人)
    else (添加并推送)
        : 获取全部的关注人;
        : 针对全部的关注人，推送大象消息;
    endif
else (已推送)
    if (操作类型) then (添加并推送)
       : 针对前端传入的新增人员，推送大象消息;
    endif
endif
: 将前端添加的关注人添加到数据库表;
: 返回前端;
end


@enduml
