@startuml
'https://plantuml.com/sequence-diagram

autonumber
autoactivate on

Web -> BusinessDataCheckController: 前端请求
BusinessDataCheckController -> RelatedTransactionRuleApplication : 调用接口，生成关联交易规则
RelatedTransactionRuleApplication -> VoucherRuleProcess.generateVoucherRule : 调用关联交易报数规则生成流程
VoucherRuleProcess.generateVoucherRule -> VoucherRuleProcess.paramValid : 参数校验
VoucherRuleProcess.paramValid --> VoucherRuleProcess.generateVoucherRule : return
alt 校验不通过
    VoucherRuleProcess.generateVoucherRule -> VoucherRuleProcess.generateVoucherRule : 判断
    VoucherRuleProcess.generateVoucherRule --> RelatedTransactionRuleApplication : return
end
VoucherRuleProcess.generateVoucherRule -> VoucherRuleProcess.isGenerateVoucherRule : 判断是否生成规则（生成结算规则的判定条件和税金规则的判定条件）
VoucherRuleProcess.isGenerateVoucherRule --> VoucherRuleProcess.generateVoucherRule : return
alt 不需要生成规则
    VoucherRuleProcess.generateVoucherRule -> VoucherRuleProcess.generateVoucherRule : 判断
    VoucherRuleProcess.generateVoucherRule --> RelatedTransactionRuleApplication : return
end
VoucherRuleProcess.generateVoucherRule -> VoucherRuleProcess.constructVourcherRule : 构造报数规则
VoucherRuleProcess.constructVourcherRule --> VoucherRuleProcess.generateVoucherRule : return
VoucherRuleProcess.generateVoucherRule -> VoucherRuleProcess.createThreeElement : 补充对应的三要素
VoucherRuleProcess.createThreeElement --> VoucherRuleProcess.generateVoucherRule : return
VoucherRuleProcess.generateVoucherRule -> VoucherRuleProcess.saveVoucherRule : 保存凭证规则（包含草稿数据和正式数据）
VoucherRuleProcess.saveVoucherRule --> VoucherRuleProcess.generateVoucherRule : return
VoucherRuleProcess.generateVoucherRule -> VoucherRuleProcess.associateInfo : 关联瞭望台相关信息（报数场景、报数需求）
VoucherRuleProcess.associateInfo --> VoucherRuleProcess.generateVoucherRule : return
VoucherRuleProcess.generateVoucherRule -> VoucherRuleProcess.createBackgroundRule : 创建后台规则
VoucherRuleProcess.createBackgroundRule --> VoucherRuleProcess.generateVoucherRule : return
VoucherRuleProcess.generateVoucherRule -> VoucherRuleProcess.updateThreeElementVersion : 升级三要素版本
VoucherRuleProcess.updateThreeElementVersion --> VoucherRuleProcess.generateVoucherRule : return

VoucherRuleProcess.generateVoucherRule --> RelatedTransactionRuleApplication : return

RelatedTransactionRuleApplication -> EntryRuleDomainService.isNeedCreateRelatedTransactionEntryRule : 判断是否需要创建关联交易入账规则
EntryRuleDomainService.isNeedCreateRelatedTransactionEntryRule --> RelatedTransactionRuleApplication: return
alt 不需要创建
    RelatedTransactionRuleApplication -> RelatedTransactionRuleApplication : 判断
    RelatedTransactionRuleApplication --> Web :return
end

EntryRuleDomainService.isNeedCreateRelatedTransactionEntryRule --> RelatedTransactionRuleApplication : return
RelatedTransactionRuleApplication -> EntryRuleDomainService.saveRelatedTransactionEntryRule: 保存关联交易规则
EntryRuleDomainService.saveRelatedTransactionEntryRule --> RelatedTransactionRuleApplication  : return
RelatedTransactionRuleApplication -> EntryRuleDomainService.updateRelation: 更新关联交易规则与入账规则的关系
EntryRuleDomainService.updateRelation --> RelatedTransactionRuleApplication : return
RelatedTransactionRuleApplication --> Web : return





@enduml