@startuml
'https://plantuml.com/activity-diagram-beta

start
:页面触发关联交易结算规则生成;

if (<color:red><b>是否满足关联交易结算判定条件) then (满足)
     note right
        <color:red><b>“是否满足关联交易结算判定条件”:<color:red>
        当【关联交易方向】为“应收方”且【关联交易金额类型】为“确认应收”，
        或者【关联交易方向】为“应付方”且【关联交易金额类型】为“确认应付”，
        且关联交易场景的是否关联交易系统结算为“是”时，
        需要生成关联交易结算报数规则的报数规则
     end note
    if (是否存在关联交易结算报数规则) then (存在)
        : 更新关联交易结算报数规则与原报数规则的关系|
    else (不存在)
        if (关联交易结算三要素是否存在) then (不存在)
            : 生成关联交易结算的三要素|
        endif
        : 生成关联交易结算报数规则|
    endif
else (不满足)
    : 不生成关联交易结算入账规则;
    stop
endif
note right
    <color:red><b>“是否唯一键冲突”:<color:red>
    入账规则的唯一键在数据库并没有做唯一键约束，而是通过代码逻辑做的判断。
    唯一键为是入账规则的所有业务字段(去除创建人创建时间等字段)
end note
if (是否存在关联交易结算入账规则) then (存在)
    if (<color:red><b>是否唯一键冲突) then (冲突)
        : 更新关联交易结算入账规则与原入账规则的关系|
    else (不冲突)

    endif
else (不存在)
endif
: 生成关联交易结算入账规则|
stop

@enduml
